apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus-gcs-server
    spec:
      containers:
        - name: nexus
          image: heryudi/nexus3-gcs:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-volume
              mountPath: /nexus-data
      volumes:
        - name: nexus-volume
          emptyDir: {}