apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: default
  labels:
    app: nexus-gcs-server
spec:
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app: nexus-gcs-server
  type: LoadBalancer
  loadBalancerIP: ""
